name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: 54.199.159.101
        port: 22
        username: ubuntu
        key: ${{ secrets.AWS_LS_PASSWORD }}
        script: |
          whoami
          sudo -i
          cd ../home/gotojapan.co/public_html
          ls -al
          killall ssh-agent
          eval `ssh-agent`
          ssh-add -D && ssh-add ~/.ssh/github_rsa
          git reset --hard HEAD
          git checkout main
          git pull origin main
          composer update
          php artisan migrate --force
          php artisan optimize:clear
          php artisan opcache:clear
          php artisan opcache:status
          chmod -R 755 storage
    - name: Deploy success
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Deploy completed"