name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ec2-52-194-223-217.ap-northeast-1.compute.amazonaws.com
        port: 22
        username: ubuntu
        key: ${{ secrets.AWS_EC2_CI }}
        script: |
          whoami
          sudo -i
          cd /var/www/html/
          ls -al
          killall ssh-agent
          eval `ssh-agent`
          ssh-add -D && ssh-add ~/.ssh/git_ci
          git reset --hard HEAD
          git checkout main
          git pull origin main
          composer update
          php artisan migrate --force
          php artisan optimize:clear
          php artisan opcache:clear
          php artisan opcache:status
          chmod -R 755 storage
    - name: Deploy success
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Deploy completed"
